name: Minetrix
main: net.lelux.minetrix.Main
version: ${project.version}
api-version: '1.13'
softdepend: [ ChatItem ]
commands:
  reloadminetrix:
    description: Reload Minetrix config
    ussage: /<command>
